# Generated by Django 3.2.12 on 2022-05-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, default=True, upload_to='moviephoto')),
                ('mname', models.CharField(max_length=90)),
                ('ticket_price', models.IntegerField()),
                ('description', models.TextField()),
                ('Trailer_link', models.CharField(max_length=150)),
                ('language', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('movie_Type', models.CharField(max_length=50)),
                ('Release_date', models.DateField()),
            ],
        ),
    ]
